port = "8090"
jwtKey = "asdfklñk21323kl"
server = "localhost:27017"
database = "veterinary"
frontendUrl = "http://136.0.111.230:3000"
Email = "undogtor@gmail.com"
EmailSmtp = "smtp.gmail.com"
EmailPassword = "UnDogtor.2021" 
logoUrl = "https://i.ibb.co/9bT3dJ0/logo.png"